QT       += core gui
QT += widgets axcontainer
QMAKE_CFLAGS += -std=c99
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

LIBS += -L./lib -lSDL2
LIBS += -L./lib -lSDL2main
LIBS += -L./lib -lSDL2_test

DEFINES += LV_CONF_INCLUDE_SIMPLE
DEFINES += WIN32

INCLUDEPATH += $$PWD/include
INCLUDEPATH += $$PWD/lvgl
INCLUDEPATH += $$PWD/lv_demos
#INCLUDEPATH += $$PWD/lv_drivers

SOURCES += main.c \
    lvgl/src/core/lv_obj.c \
    lvgl/src/core/lv_group.c \
    lvgl/src/core/lv_obj_class.c \
    lvgl/src/core/lv_obj_draw.c \
    lvgl/src/core/lv_obj_event.c \
    lvgl/src/core/lv_obj_id_builtin.c \
    lvgl/src/core/lv_obj_pos.c \
    lvgl/src/core/lv_obj_property.c \
    lvgl/src/core/lv_obj_scroll.c \
    lvgl/src/core/lv_obj_style.c \
    lvgl/src/core/lv_obj_style_gen.c \
    lvgl/src/core/lv_obj_tree.c \
    lvgl/src/core/lv_refr.c \
    lvgl/src/display/lv_display.c \
    lvgl/src/draw/lv_draw.c \
    lvgl/src/draw/lv_draw_arc.c \
    lvgl/src/draw/lv_draw_buf.c \
    lvgl/src/draw/lv_draw_image.c \
    lvgl/src/draw/lv_draw_label.c \
    lvgl/src/draw/lv_draw_line.c \
    lvgl/src/draw/lv_draw_mask.c \
    lvgl/src/draw/lv_draw_rect.c \
    lvgl/src/draw/lv_draw_triangle.c \
    lvgl/src/draw/lv_draw_vector.c \
    lvgl/src/draw/lv_image_buf.c \
    lvgl/src/draw/lv_image_decoder.c \
    lvgl/src/draw/sw/lv_draw_sw.c \
    lvgl/src/draw/sw/lv_draw_sw_arc.c \
    lvgl/src/draw/sw/lv_draw_sw_border.c \
    lvgl/src/draw/sw/lv_draw_sw_box_shadow.c \
    lvgl/src/draw/sw/lv_draw_sw_fill.c \
    lvgl/src/draw/sw/lv_draw_sw_gradient.c \
    lvgl/src/draw/sw/lv_draw_sw_img.c \
    lvgl/src/draw/sw/lv_draw_sw_letter.c \
    lvgl/src/draw/sw/lv_draw_sw_line.c \
    lvgl/src/draw/sw/lv_draw_sw_mask.c \
    lvgl/src/draw/sw/lv_draw_sw_mask_rect.c \
    lvgl/src/draw/sw/lv_draw_sw_transform.c \
    lvgl/src/draw/sw/lv_draw_sw_triangle.c \
    lvgl/src/draw/sw/lv_draw_sw_vector.c \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend.c \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_argb8888.c \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb565.c \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb888.c \
    lvgl/src/draw/sdl/lv_draw_sdl.c \
    lvgl/src/draw/nxp/vglite/lv_draw_buf_vglite.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_arc.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_border.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_fill.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_img.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_label.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_layer.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_line.c \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite_triangle.c \
    lvgl/src/draw/nxp/vglite/lv_vglite_buf.c \
    lvgl/src/draw/nxp/vglite/lv_vglite_matrix.c \
    lvgl/src/draw/nxp/vglite/lv_vglite_path.c \
    lvgl/src/draw/nxp/vglite/lv_vglite_utils.c \
    lvgl/src/draw/vg_lite/lv_draw_buf_vg_lite.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_arc.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_border.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_box_shadow.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_fill.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_img.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_label.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_layer.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_line.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_mask_rect.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_triangle.c \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_vector.c \
    lvgl/src/draw/vg_lite/lv_vg_lite_decoder.c \
    lvgl/src/draw/vg_lite/lv_vg_lite_math.c \
    lvgl/src/draw/vg_lite/lv_vg_lite_path.c \
    lvgl/src/draw/vg_lite/lv_vg_lite_utils.c \
    lvgl/src/draw/nxp/pxp/lv_draw_buf_pxp.c \
    lvgl/src/draw/nxp/pxp/lv_draw_pxp.c \
    lvgl/src/draw/nxp/pxp/lv_draw_pxp_fill.c \
    lvgl/src/draw/nxp/pxp/lv_draw_pxp_img.c \
    lvgl/src/draw/nxp/pxp/lv_draw_pxp_layer.c \
    lvgl/src/draw/nxp/pxp/lv_pxp_cfg.c \
    lvgl/src/draw/nxp/pxp/lv_pxp_osa.c \
    lvgl/src/draw/nxp/pxp/lv_pxp_utils.c \
    lvgl/src/drivers/sdl/lv_sdl_keyboard.c \
    lvgl/src/drivers/sdl/lv_sdl_mouse.c \
    lvgl/src/drivers/sdl/lv_sdl_mousewheel.c \
    lvgl/src/drivers/sdl/lv_sdl_window.c \
    lvgl/src/drivers/windows/lv_windows_context.c \
    lvgl/src/drivers/windows/lv_windows_display.c \
    lvgl/src/drivers/windows/lv_windows_input.c \
    lvgl/src/drivers/x11/lv_x11_display.c \
    lvgl/src/drivers/x11/lv_x11_input.c \
    lvgl/src/drivers/display/drm/lv_linux_drm.c \
    lvgl/src/drivers/display/fb/lv_linux_fbdev.c \
    lvgl/src/drivers/display/ili9341/lv_ili9341.c \
    lvgl/src/drivers/display/lcd/lv_lcd_generic_mipi.c \
    lvgl/src/drivers/display/st7735/lv_st7735.c \
    lvgl/src/drivers/display/st7789/lv_st7789.c \
    lvgl/src/drivers/display/st7796/lv_st7796.c \
    lvgl/src/drivers/display/tft_espi/lv_tft_espi.cpp \
    lvgl/src/font/lv_binfont_loader.c \
    lvgl/src/font/lv_font.c \
    lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c \
    lvgl/src/font/lv_font_fmt_txt.c \
    lvgl/src/font/lv_font_montserrat_8.c \
    lvgl/src/font/lv_font_montserrat_10.c \
    lvgl/src/font/lv_font_montserrat_12.c \
    lvgl/src/font/lv_font_montserrat_14.c \
    lvgl/src/font/lv_font_montserrat_16.c \
    lvgl/src/font/lv_font_montserrat_18.c \
    lvgl/src/font/lv_font_montserrat_20.c \
    lvgl/src/font/lv_font_montserrat_22.c \
    lvgl/src/font/lv_font_montserrat_24.c \
    lvgl/src/font/lv_font_montserrat_26.c \
    lvgl/src/font/lv_font_montserrat_28.c \
    lvgl/src/font/lv_font_montserrat_28_compressed.c \
    lvgl/src/font/lv_font_montserrat_30.c \
    lvgl/src/font/lv_font_montserrat_32.c \
    lvgl/src/font/lv_font_montserrat_34.c \
    lvgl/src/font/lv_font_montserrat_36.c \
    lvgl/src/font/lv_font_montserrat_38.c \
    lvgl/src/font/lv_font_montserrat_40.c \
    lvgl/src/font/lv_font_montserrat_42.c \
    lvgl/src/font/lv_font_montserrat_44.c \
    lvgl/src/font/lv_font_montserrat_46.c \
    lvgl/src/font/lv_font_montserrat_48.c \
    lvgl/src/font/lv_font_simsun_16_cjk.c \
    lvgl/src/font/lv_font_unscii_8.c \
    lvgl/src/font/lv_font_unscii_16.c \
    lvgl/src/indev/lv_indev.c \
    lvgl/src/indev/lv_indev_scroll.c \
    lvgl/src/layouts/lv_layout.c \
    lvgl/src/layouts/flex/lv_flex.c \
    lvgl/src/layouts/grid/lv_grid.c \
    lvgl/src/misc/lv_anim.c \
    lvgl/src/misc/lv_anim_timeline.c \
    lvgl/src/misc/lv_area.c \
    lvgl/src/misc/lv_array.c \
    lvgl/src/misc/lv_async.c \
    lvgl/src/misc/lv_bidi.c \
    lvgl/src/misc/lv_color.c \
    lvgl/src/misc/lv_color_op.c \
    lvgl/src/misc/lv_event.c \
    lvgl/src/misc/lv_fs.c \
    lvgl/src/misc/lv_ll.c \
    lvgl/src/misc/lv_log.c \
    lvgl/src/misc/lv_lru.c \
    lvgl/src/misc/lv_math.c \
    lvgl/src/misc/lv_palette.c \
    lvgl/src/misc/lv_profiler_builtin.c \
    lvgl/src/misc/lv_rb.c \
    lvgl/src/misc/lv_style.c \
    lvgl/src/misc/lv_style_gen.c \
    lvgl/src/misc/lv_templ.c \
    lvgl/src/misc/lv_text.c \
    lvgl/src/misc/lv_text_ap.c \
    lvgl/src/misc/lv_timer.c \
    lvgl/src/misc/lv_utils.c \
    lvgl/src/misc/cache/_lv_cache_lru_rb.c \
    lvgl/src/misc/cache/lv_cache.c \
    lvgl/src/misc/cache/lv_cache_entry.c \
    lvgl/src/misc/cache/lv_image_cache.c \
    lvgl/src/osal/lv_cmsis_rtos2.c \
    lvgl/src/osal/lv_freertos.c \
    lvgl/src/osal/lv_os_none.c \
    lvgl/src/osal/lv_pthread.c \
    lvgl/src/osal/lv_rtthread.c \
    lvgl/src/osal/lv_windows.c \
    lvgl/src/others/file_explorer/lv_file_explorer.c \
    lvgl/src/others/fragment/lv_fragment.c \
    lvgl/src/others/fragment/lv_fragment_manager.c \
    lvgl/src/others/gridnav/lv_gridnav.c \
    lvgl/src/others/ime/lv_ime_pinyin.c \
    lvgl/src/others/imgfont/lv_imgfont.c \
    lvgl/src/others/monkey/lv_monkey.c \
    lvgl/src/others/observer/lv_observer.c \
    lvgl/src/others/snapshot/lv_snapshot.c \
    lvgl/src/others/sysmon/lv_sysmon.c \
    lvgl/src/others/vg_lite_tvg/vg_lite_tvg.cpp \
    lvgl/src/others/vg_lite_tvg/vg_lite_matrix.c \
    lvgl/src/stdlib/lv_mem.c \
    lvgl/src/stdlib/builtin/lv_mem_core_builtin.c \
    lvgl/src/stdlib/builtin/lv_sprintf_builtin.c \
    lvgl/src/stdlib/builtin/lv_string_builtin.c \
    lvgl/src/stdlib/builtin/lv_tlsf.c \
    lvgl/src/stdlib/clib/lv_mem_core_clib.c \
    lvgl/src/stdlib/clib/lv_sprintf_clib.c \
    lvgl/src/stdlib/clib/lv_string_clib.c \
    lvgl/src/stdlib/micropython/lv_mem_core_micropython.c \
    lvgl/src/stdlib/rtthread/lv_mem_core_rtthread.c \
    lvgl/src/stdlib/rtthread/lv_sprintf_rtthread.c \
    lvgl/src/stdlib/rtthread/lv_string_rtthread.c \
    lvgl/src/themes/lv_theme.c \
    lvgl/src/themes/default/lv_theme_default.c \
    lvgl/src/themes/mono/lv_theme_mono.c \
    lvgl/src/themes/simple/lv_theme_simple.c \
    lvgl/src/tick/lv_tick.c \
    lvgl/src/widgets/animimage/lv_animimage.c \
    lvgl/src/widgets/arc/lv_arc.c \
    lvgl/src/widgets/bar/lv_bar.c \
    lvgl/src/widgets/button/lv_button.c \
    lvgl/src/widgets/buttonmatrix/lv_buttonmatrix.c \
    lvgl/src/widgets/calendar/lv_calendar.c \
    lvgl/src/widgets/calendar/lv_calendar_header_arrow.c \
    lvgl/src/widgets/calendar/lv_calendar_header_dropdown.c \
    lvgl/src/widgets/canvas/lv_canvas.c \
    lvgl/src/widgets/chart/lv_chart.c \
    lvgl/src/widgets/checkbox/lv_checkbox.c \
    lvgl/src/widgets/dropdown/lv_dropdown.c \
    lvgl/src/widgets/image/lv_image.c \
    lvgl/src/widgets/imagebutton/lv_imagebutton.c \
    lvgl/src/widgets/keyboard/lv_keyboard.c \
    lvgl/src/widgets/label/lv_label.c \
    lvgl/src/widgets/led/lv_led.c \
    lvgl/src/widgets/line/lv_line.c \
    lvgl/src/widgets/list/lv_list.c \
    lvgl/src/widgets/menu/lv_menu.c \
    lvgl/src/widgets/msgbox/lv_msgbox.c \
    lvgl/src/widgets/objx_templ/lv_objx_templ.c \
    lvgl/src/widgets/roller/lv_roller.c \
    lvgl/src/widgets/scale/lv_scale.c \
    lvgl/src/widgets/slider/lv_slider.c \
    lvgl/src/widgets/span/lv_span.c \
    lvgl/src/widgets/spinner/lv_spinner.c \
    lvgl/src/widgets/spinbox/lv_spinbox.c \
    lvgl/src/widgets/switch/lv_switch.c \
    lvgl/src/widgets/table/lv_table.c \
    lvgl/src/widgets/tabview/lv_tabview.c \
    lvgl/src/widgets/textarea/lv_textarea.c \
    lvgl/src/widgets/tileview/lv_tileview.c \
    lvgl/src/widgets/win/lv_win.c \
    lvgl/src/lv_init.c \
    lvgl/src/libs/barcode/code128.c \
    lvgl/src/libs/barcode/lv_barcode.c \
    lvgl/src/libs/bin_decoder/lv_bin_decoder.c \
    lvgl/src/libs/bmp/lv_bmp.c \
    lvgl/src/libs/ffmpeg/lv_ffmpeg.c \
    lvgl/src/libs/fsdrv/lv_fs_cbfs.c \
    lvgl/src/libs/fsdrv/lv_fs_fatfs.c \
    lvgl/src/libs/fsdrv/lv_fs_memfs.c \
    lvgl/src/libs/fsdrv/lv_fs_posix.c \
    lvgl/src/libs/fsdrv/lv_fs_stdio.c \
    lvgl/src/libs/fsdrv/lv_fs_win32.c \
    lvgl/src/libs/gif/gifdec.c \
    lvgl/src/libs/gif/lv_gif.c \
    lvgl/src/libs/libpng/lv_libpng.c \
    lvgl/src/libs/lodepng/lodepng.c \
    lvgl/src/libs/lodepng/lv_lodepng.c \
    lvgl/src/libs/lz4/lz4.c \
    lvgl/src/libs/qrcode/lv_qrcode.c \
    lvgl/src/libs/qrcode/qrcodegen.c \
    lvgl/src/libs/tjpgd/lv_tjpgd.c \
    lvgl/src/libs/tjpgd/tjpgd.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_arc.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_border.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_fill.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_image.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_label.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_line.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_mask_rectangle.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_triangle.c \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_utils.c \
    lvgl/src/drivers/nuttx/lv_nuttx_cache.c \
    lvgl/src/drivers/nuttx/lv_nuttx_entry.c \
    lvgl/src/drivers/nuttx/lv_nuttx_fbdev.c \
    lvgl/src/drivers/nuttx/lv_nuttx_lcd.c \
    lvgl/src/drivers/nuttx/lv_nuttx_libuv.c \
    lvgl/src/drivers/nuttx/lv_nuttx_profiler.c \
    lvgl/src/drivers/nuttx/lv_nuttx_touchscreen.c \
    lvgl/src/drivers/evdev/lv_evdev.c \
    lvgl/demos/lv_demos.c \
    lvgl/demos/widgets/lv_demo_widgets.c \
    lvgl/demos/widgets/assets/img_clothes.c \
    lvgl/demos/widgets/assets/img_demo_widgets_avatar.c \
    lvgl/demos/widgets/assets/img_demo_widgets_needle.c \
    lvgl/demos/widgets/assets/img_lvgl_logo.c \
    lvgl/demos/music/lv_demo_music.c \
    lvgl/demos/music/lv_demo_music_list.c \
    lvgl/demos/music/lv_demo_music_main.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_corner_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_list_pause.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_list_pause_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_list_play.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_list_play_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_loop.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_loop_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_next.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_next_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_pause.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_pause_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_play.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_play_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_prev.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_prev_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_rnd.c \
    lvgl/demos/music/assets/img_lv_demo_music_btn_rnd_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_corner_left.c \
    lvgl/demos/music/assets/img_lv_demo_music_corner_left_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_corner_right.c \
    lvgl/demos/music/assets/img_lv_demo_music_corner_right_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_cover_1.c \
    lvgl/demos/music/assets/img_lv_demo_music_cover_1_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_cover_2.c \
    lvgl/demos/music/assets/img_lv_demo_music_cover_2_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_cover_3.c \
    lvgl/demos/music/assets/img_lv_demo_music_cover_3_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_1.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_1_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_2.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_2_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_3.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_3_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_4.c \
    lvgl/demos/music/assets/img_lv_demo_music_icon_4_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_list_border.c \
    lvgl/demos/music/assets/img_lv_demo_music_list_border_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_logo.c \
    lvgl/demos/music/assets/img_lv_demo_music_slider_knob.c \
    lvgl/demos/music/assets/img_lv_demo_music_slider_knob_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_wave_bottom.c \
    lvgl/demos/music/assets/img_lv_demo_music_wave_bottom_large.c \
    lvgl/demos/music/assets/img_lv_demo_music_wave_top.c \
    lvgl/demos/music/assets/img_lv_demo_music_wave_top_large.c \
    lvgl/demos/keypad_encoder/lv_demo_keypad_encoder.c \
    lvgl/demos/benchmark/lv_demo_benchmark.c \
    lvgl/demos/benchmark/assets/img_benchmark_cogwheel_alpha256.c \
    lvgl/demos/benchmark/assets/img_benchmark_cogwheel_argb.c \
    lvgl/demos/benchmark/assets/img_benchmark_cogwheel_indexed16.c \
    lvgl/demos/benchmark/assets/img_benchmark_cogwheel_rgb.c \
    lvgl/demos/benchmark/assets/lv_font_benchmark_montserrat_12_compr_az.c.c \
    lvgl/demos/benchmark/assets/lv_font_benchmark_montserrat_16_compr_az.c.c \
    lvgl/demos/benchmark/assets/lv_font_benchmark_montserrat_28_compr_az.c.c \
    lvgl/demos/flex_layout/lv_demo_flex_layout_ctrl_pad.c \
    lvgl/demos/flex_layout/lv_demo_flex_layout_flex_loader.c \
    lvgl/demos/flex_layout/lv_demo_flex_layout_main.c \
    lvgl/demos/flex_layout/lv_demo_flex_layout_view.c \
    lvgl/demos/flex_layout/lv_demo_flex_layout_view_child_node.c \
    lvgl/demos/flex_layout/lv_demo_flex_layout_view_ctrl_pad.c \
    lvgl/demos/multilang/lv_demo_multilang.c \
    lvgl/demos/multilang/assets/img_multilang_like.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_1.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_2.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_3.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_4.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_5.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_6.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_7.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_8.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_9.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_10.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_11.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_12.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_13.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_14.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_15.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_16.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_17.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_18.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_19.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_22.c \
    lvgl/demos/multilang/assets/avatars/img_multilang_avatar_25.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_artist_palette.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_books.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_camera_with_flash.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_cat_face.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_deciduous_tree.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_dog_face.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_earth_globe_europe_africa.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_flexed_biceps.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_movie_camera.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_red_heart.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_rocket.c \
    lvgl/demos/multilang/assets/emojis/img_emoji_soccer_ball.c \
    lvgl/demos/multilang/assets/fonts/font_multilang_large.c \
    lvgl/demos/multilang/assets/fonts/font_multilang_small.c \
    lvgl/demos/render/lv_demo_render.c \
    lvgl/demos/render/assets/img_render_arc_bg.c \
    lvgl/demos/render/assets/img_render_lvgl_logo_argb8888.c \
    lvgl/demos/render/assets/img_render_lvgl_logo_rgb565.c \
    lvgl/demos/render/assets/img_render_lvgl_logo_rgb888.c \
    lvgl/demos/render/assets/img_render_lvgl_logo_xrgb8888.c \
    lvgl/demos/scroll/lv_demo_scroll.c \
    lvgl/demos/stress/lv_demo_stress.c \
    lvgl/demos/transform/lv_demo_transform.c \
    lvgl/demos/transform/assets/img_transform_avatar_15.c

HEADERS += \
    include/SDL2/begin_code.h \
    include/SDL2/close_code.h \
    include/SDL2/SDL.h \
    include/SDL2/SDL_assert.h \
    include/SDL2/SDL_atomic.h \
    include/SDL2/SDL_audio.h \
    include/SDL2/SDL_bits.h \
    include/SDL2/SDL_blendmode.h \
    include/SDL2/SDL_clipboard.h \
    include/SDL2/SDL_config.h \
    include/SDL2/SDL_cpuinfo.h \
    include/SDL2/SDL_egl.h \
    include/SDL2/SDL_endian.h \
    include/SDL2/SDL_error.h \
    include/SDL2/SDL_events.h \
    include/SDL2/SDL_filesystem.h \
    include/SDL2/SDL_gamecontroller.h \
    include/SDL2/SDL_gesture.h \
    include/SDL2/SDL_haptic.h \
    include/SDL2/SDL_hints.h \
    include/SDL2/SDL_joystick.h \
    include/SDL2/SDL_keyboard.h \
    include/SDL2/SDL_keycode.h \
    include/SDL2/SDL_loadso.h \
    include/SDL2/SDL_log.h \
    include/SDL2/SDL_main.h \
    include/SDL2/SDL_messagebox.h \
    include/SDL2/SDL_mouse.h \
    include/SDL2/SDL_mutex.h \
    include/SDL2/SDL_name.h \
    include/SDL2/SDL_opengl.h \
    include/SDL2/SDL_opengl_glext.h \
    include/SDL2/SDL_opengles.h \
    include/SDL2/SDL_opengles2.h \
    include/SDL2/SDL_opengles2_gl2.h \
    include/SDL2/SDL_opengles2_gl2ext.h \
    include/SDL2/SDL_opengles2_gl2platform.h \
    include/SDL2/SDL_opengles2_khrplatform.h \
    include/SDL2/SDL_pixels.h \
    include/SDL2/SDL_platform.h \
    include/SDL2/SDL_power.h \
    include/SDL2/SDL_quit.h \
    include/SDL2/SDL_rect.h \
    include/SDL2/SDL_render.h \
    include/SDL2/SDL_revision.h \
    include/SDL2/SDL_rwops.h \
    include/SDL2/SDL_scancode.h \
    include/SDL2/SDL_shape.h \
    include/SDL2/SDL_stdinc.h \
    include/SDL2/SDL_surface.h \
    include/SDL2/SDL_system.h \
    include/SDL2/SDL_syswm.h \
    include/SDL2/SDL_test.h \
    include/SDL2/SDL_test_assert.h \
    include/SDL2/SDL_test_common.h \
    include/SDL2/SDL_test_compare.h \
    include/SDL2/SDL_test_crc32.h \
    include/SDL2/SDL_test_font.h \
    include/SDL2/SDL_test_fuzzer.h \
    include/SDL2/SDL_test_harness.h \
    include/SDL2/SDL_test_images.h \
    include/SDL2/SDL_test_log.h \
    include/SDL2/SDL_test_md5.h \
    include/SDL2/SDL_test_memory.h \
    include/SDL2/SDL_test_random.h \
    include/SDL2/SDL_thread.h \
    include/SDL2/SDL_timer.h \
    include/SDL2/SDL_touch.h \
    include/SDL2/SDL_types.h \
    include/SDL2/SDL_version.h \
    include/SDL2/SDL_video.h \
    include/SDL2/SDL_vulkan.h \
    lvgl/src/core/lv_global.h \
    lvgl/src/core/lv_group.h \
    lvgl/src/core/lv_obj.h \
    lvgl/src/core/lv_obj_class.h \
    lvgl/src/core/lv_obj_draw.h \
    lvgl/src/core/lv_obj_event.h \
    lvgl/src/core/lv_obj_pos.h \
    lvgl/src/core/lv_obj_property.h \
    lvgl/src/core/lv_obj_scroll.h \
    lvgl/src/core/lv_obj_style.h \
    lvgl/src/core/lv_obj_style_gen.h \
    lvgl/src/core/lv_obj_tree.h \
    lvgl/src/core/lv_refr.h \
    lvgl/src/display/lv_display.h \
    lvgl/src/display/lv_display_private.h \
    lvgl/src/draw/lv_draw.h \
    lvgl/src/draw/lv_draw_arc.h \
    lvgl/src/draw/lv_draw_buf.h \
    lvgl/src/draw/lv_draw_image.h \
    lvgl/src/draw/lv_draw_label.h \
    lvgl/src/draw/lv_draw_line.h \
    lvgl/src/draw/lv_draw_mask.h \
    lvgl/src/draw/lv_draw_rect.h \
    lvgl/src/draw/lv_draw_triangle.h \
    lvgl/src/draw/lv_draw_vector.h \
    lvgl/src/draw/lv_image_buf.h \
    lvgl/src/draw/lv_image_decoder.h \
    lvgl/src/draw/sw/lv_draw_sw.h \
    lvgl/src/draw/sw/lv_draw_sw_gradient.h \
    lvgl/src/draw/sw/lv_draw_sw_mask.h \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend.h \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_argb8888.h \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb565.h \
    lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb888.h \
    lvgl/src/draw/sw/blend/arm2d/lv_blend_arm2d.h \
    lvgl/src/draw/sw/blend/arm2d/lv_blend_helium.h \
    lvgl/src/draw/sw/blend/neon/lv_blend_neon.h \
    lvgl/src/draw/sw/blend/neon/lv_blend_neon.S \
    lvgl/src/draw/sdl/lv_draw_sdl.h \
    lvgl/src/draw/nxp/vglite/lv_draw_vglite.h \
    lvgl/src/draw/nxp/vglite/lv_vglite_buf.h \
    lvgl/src/draw/nxp/vglite/lv_vglite_matrix.h \
    lvgl/src/draw/nxp/vglite/lv_vglite_path.h \
    lvgl/src/draw/nxp/vglite/lv_vglite_utils.h \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite.h \
    lvgl/src/draw/vg_lite/lv_draw_vg_lite_type.h \
    lvgl/src/draw/vg_lite/lv_vg_lite_decoder.h \
    lvgl/src/draw/vg_lite/lv_vg_lite_math.h \
    lvgl/src/draw/vg_lite/lv_vg_lite_path.h \
    lvgl/src/draw/vg_lite/lv_vg_lite_utils.h \
    lvgl/src/draw/nxp/pxp/lv_draw_pxp.h \
    lvgl/src/draw/nxp/pxp/lv_pxp_cfg.h \
    lvgl/src/draw/nxp/pxp/lv_pxp_osa.h \
    lvgl/src/draw/nxp/pxp/lv_pxp_utils.h \
    lvgl/src/draw/sw/arm2d/lv_draw_sw_arm2d.h \
    lvgl/src/draw/sw/arm2d/lv_draw_sw_helium.h \
    lvgl/src/drivers/sdl/lv_sdl_keyboard.h \
    lvgl/src/drivers/sdl/lv_sdl_mouse.h \
    lvgl/src/drivers/sdl/lv_sdl_mousewheel.h \
    lvgl/src/drivers/sdl/lv_sdl_window.h \
    lvgl/src/drivers/windows/lv_windows_context.h \
    lvgl/src/drivers/windows/lv_windows_display.h \
    lvgl/src/drivers/windows/lv_windows_input.h \
    lvgl/src/drivers/x11/lv_x11.h \
    lvgl/src/drivers/display/drm/lv_linux_drm.h \
    lvgl/src/drivers/display/fb/lv_linux_fbdev.h \
    lvgl/src/drivers/display/ili9341/lv_ili9341.h \
    lvgl/src/drivers/display/lcd/lv_lcd_generic_mipi.h \
    lvgl/src/drivers/display/st7735/lv_st7735.h \
    lvgl/src/drivers/display/st7789/lv_st7789.h \
    lvgl/src/drivers/display/st7796/lv_st7796.h \
    lvgl/src/drivers/display/tft_espi/lv_tft_espi.h \
    lvgl/src/font/lv_binfont_loader.h \
    lvgl/src/font/lv_font.h \
    lvgl/src/font/lv_font_fmt_txt.h \
    lvgl/src/font/lv_symbol_def.h \
    lvgl/src/indev/lv_indev.h \
    lvgl/src/indev/lv_indev_private.h \
    lvgl/src/indev/lv_indev_scroll.h \
    lvgl/src/layouts/lv_layout.h \
    lvgl/src/layouts/flex/lv_flex.h \
    lvgl/src/layouts/grid/lv_grid.h \
    lvgl/src/misc/lv_anim.h \
    lvgl/src/misc/lv_anim_timeline.h \
    lvgl/src/misc/lv_area.h \
    lvgl/src/misc/lv_array.h \
    lvgl/src/misc/lv_assert.h \
    lvgl/src/misc/lv_async.h \
    lvgl/src/misc/lv_bidi.h \
    lvgl/src/misc/lv_color.h \
    lvgl/src/misc/lv_color_op.h \
    lvgl/src/misc/lv_event.h \
    lvgl/src/misc/lv_fs.h \
    lvgl/src/misc/lv_ll.h \
    lvgl/src/misc/lv_log.h \
    lvgl/src/misc/lv_lru.h \
    lvgl/src/misc/lv_math.h \
    lvgl/src/misc/lv_palette.h \
    lvgl/src/misc/lv_profiler.h \
    lvgl/src/misc/lv_profiler_builtin.h \
    lvgl/src/misc/lv_rb.h \
    lvgl/src/misc/lv_style.h \
    lvgl/src/misc/lv_style_gen.h \
    lvgl/src/misc/lv_templ.h \
    lvgl/src/misc/lv_text.h \
    lvgl/src/misc/lv_text_ap.h \
    lvgl/src/misc/lv_timer.h \
    lvgl/src/misc/lv_types.h \
    lvgl/src/misc/lv_utils.h \
    lvgl/src/misc/cache/_lv_cache_lru_rb.h \
    lvgl/src/misc/cache/lv_cache.h \
    lvgl/src/misc/cache/lv_cache_entry.h \
    lvgl/src/misc/cache/lv_cache_entry_private.h \
    lvgl/src/misc/cache/lv_cache_private.h \
    lvgl/src/misc/cache/lv_image_cache.h \
    lvgl/src/osal/lv_cmsis_rtos2.h \
    lvgl/src/osal/lv_freertos.h \
    lvgl/src/osal/lv_os.h \
    lvgl/src/osal/lv_os_none.h \
    lvgl/src/osal/lv_pthread.h \
    lvgl/src/osal/lv_rtthread.h \
    lvgl/src/osal/lv_windows.h \
    lvgl/src/others/file_explorer/lv_file_explorer.h \
    lvgl/src/others/fragment/lv_fragment.h \
    lvgl/src/others/gridnav/lv_gridnav.h \
    lvgl/src/others/ime/lv_ime_pinyin.h \
    lvgl/src/others/imgfont/lv_imgfont.h \
    lvgl/src/others/monkey/lv_monkey.h \
    lvgl/src/others/observer/lv_observer.h \
    lvgl/src/others/snapshot/lv_snapshot.h \
    lvgl/src/others/sysmon/lv_sysmon.h \
    lvgl/src/others/vg_lite_tvg/vg_lite.h \
    lvgl/src/stdlib/lv_mem.h \
    lvgl/src/stdlib/lv_sprintf.h \
    lvgl/src/stdlib/lv_string.h \
    lvgl/src/stdlib/builtin/lv_tlsf.h \
    lvgl/src/themes/lv_theme.h \
    lvgl/src/themes/default/lv_theme_default.h \
    lvgl/src/themes/mono/lv_theme_mono.h \
    lvgl/src/themes/simple/lv_theme_simple.h \
    lvgl/src/tick/lv_tick.h \
    lvgl/src/widgets/animimage/lv_animimage.h \
    lvgl/src/widgets/arc/lv_arc.h \
    lvgl/src/widgets/bar/lv_bar.h \
    lvgl/src/widgets/button/lv_button.h \
    lvgl/src/widgets/buttonmatrix/lv_buttonmatrix.h \
    lvgl/src/widgets/calendar/lv_calendar.h \
    lvgl/src/widgets/calendar/lv_calendar_header_arrow.h \
    lvgl/src/widgets/calendar/lv_calendar_header_dropdown.h \
    lvgl/src/widgets/canvas/lv_canvas.h \
    lvgl/src/widgets/chart/lv_chart.h \
    lvgl/src/widgets/checkbox/lv_checkbox.h \
    lvgl/src/widgets/dropdown/lv_dropdown.h \
    lvgl/src/widgets/image/lv_image.h \
    lvgl/src/widgets/imagebutton/lv_imagebutton.h \
    lvgl/src/widgets/keyboard/lv_keyboard.h \
    lvgl/src/widgets/label/lv_label.h \
    lvgl/src/widgets/led/lv_led.h \
    lvgl/src/widgets/line/lv_line.h \
    lvgl/src/widgets/list/lv_list.h \
    lvgl/src/widgets/menu/lv_menu.h \
    lvgl/src/widgets/msgbox/lv_msgbox.h \
    lvgl/src/widgets/objx_templ/lv_objx_templ.h \
    lvgl/src/widgets/roller/lv_roller.h \
    lvgl/src/widgets/scale/lv_scale.h \
    lvgl/src/widgets/slider/lv_slider.h \
    lvgl/src/widgets/span/lv_span.h \
    lvgl/src/widgets/spinner/lv_spinner.h \
    lvgl/src/widgets/spinbox/lv_spinbox.h \
    lvgl/src/widgets/switch/lv_switch.h \
    lvgl/src/widgets/table/lv_table.h \
    lvgl/src/widgets/tabview/lv_tabview.h \
    lvgl/src/widgets/textarea/lv_textarea.h \
    lvgl/src/widgets/tileview/lv_tileview.h \
    lvgl/src/widgets/win/lv_win.h \
    lvgl/src/lv_api_map.h \
    lvgl/src/lv_conf_internal.h \
    lvgl/src/lv_conf_kconfig.h \
    lvgl/src/lv_init.h \
    lvgl/src/lvgl.h \
    lvgl/src/lvgl_private.h \
    lvgl/src/libs/barcode/code128.h \
    lvgl/src/libs/barcode/lv_barcode.h \
    lvgl/src/libs/bin_decoder/lv_bin_decoder.h \
    lvgl/src/libs/bmp/lv_bmp.h \
    lvgl/src/libs/ffmpeg/lv_ffmpeg.h \
    lvgl/src/libs/fsdrv/lv_fsdrv.h \
    lvgl/src/libs/gif/gifdec.h \
    lvgl/src/libs/gif/gifdec_mve.h \
    lvgl/src/libs/gif/lv_gif.h \
    lvgl/src/libs/libpng/lv_libpng.h \
    lvgl/src/libs/lodepng/lodepng.h \
    lvgl/src/libs/lodepng/lv_lodepng.h \
    lvgl/src/libs/lz4/lz4.h \
    lvgl/src/libs/qrcode/lv_qrcode.h \
    lvgl/src/libs/qrcode/qrcodegen.h \
    lvgl/src/libs/tjpgd/lv_tjpgd.h \
    lvgl/src/libs/tjpgd/tjpgd.h \
    lvgl/src/libs/tjpgd/tjpgdcnf.h \
    lvgl/lv_conf.h \
    lvgl/lvgl.h \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d.h \
    lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_utils.h \
    lvgl/src/drivers/nuttx/lv_nuttx_cache.h \
    lvgl/src/drivers/nuttx/lv_nuttx_entry.h \
    lvgl/src/drivers/nuttx/lv_nuttx_fbdev.h \
    lvgl/src/drivers/nuttx/lv_nuttx_lcd.h \
    lvgl/src/drivers/nuttx/lv_nuttx_libuv.h \
    lvgl/src/drivers/nuttx/lv_nuttx_profiler.h \
    lvgl/src/drivers/nuttx/lv_nuttx_touchscreen.h \
    lvgl/src/drivers/evdev/lv_evdev.h \
    lvgl/demos/lv_demos.h \
    lvgl/demos/widgets/lv_demo_widgets.h \
    lvgl/demos/music/lv_demo_music.h \
    lvgl/demos/music/lv_demo_music_list.h \
    lvgl/demos/music/lv_demo_music_main.h \
    lvgl/demos/music/assets/spectrum_1.h \
    lvgl/demos/music/assets/spectrum_2.h \
    lvgl/demos/music/assets/spectrum_3.h \
    lvgl/demos/keypad_encoder/lv_demo_keypad_encoder.h \
    lvgl/demos/benchmark/lv_demo_benchmark.h \
    lvgl/demos/flex_layout/lv_demo_flex_layout.h \
    lvgl/demos/flex_layout/lv_demo_flex_layout_main.h \
    lvgl/demos/multilang/lv_demo_multilang.h \
    lvgl/demos/render/lv_demo_render.h \
    lvgl/demos/scroll/lv_demo_scroll.h \
    lvgl/demos/stress/lv_demo_stress.h \
    lvgl/demos/transform/lv_demo_transform.h
